<?php
return array (
  1 => 
  array (
    'siteid' => '1',
    'name' => '默认站点',
    'dirname' => '',
    'domain' => 'http://www.zgcfw.org.cn/',
    'site_title' => '中关村企业服务网',
    'keywords' => '中关村企业服务网，企业诊断，政府资金项目申报，涉密资质，政府基金，税收优惠策划，知识产权规划，双软、重点软件企业、高新认定，计算机系统集成资质、涉密资质、安防资质',
    'description' => '中关村企业服务网帮助企业有效地利用各项政策资源实现企业最大利益      为企业提供全方位、多层次、专业化的“行政管家”式的服务，      为企业进行专业诊断、制订融资方案、知识产权战略、财税规划和资质认证等。',
    'release_point' => '',
    'default_style' => 'default',
    'template' => 'default',
    'setting' => 'array (
  \'upload_maxsize\' => \'10480\',
  \'upload_allowext\' => \'jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf\',
  \'watermark_enable\' => \'1\',
  \'watermark_minwidth\' => \'300\',
  \'watermark_minheight\' => \'300\',
  \'watermark_img\' => \'statics/images/water//mark.png\',
  \'watermark_pct\' => \'85\',
  \'watermark_quality\' => \'80\',
  \'watermark_pos\' => \'9\',
)',
    'uuid' => '2c644e71-46c5-11e3-b209-2309c3b6463b',
    'url' => 'http://www.zgcfw.org.cn/',
  ),
  2 => 
  array (
    'siteid' => '2',
    'name' => '中关村企业服务网',
    'dirname' => 'zgccfw',
    'domain' => 'http://www.zgccfw.com/',
    'site_title' => '创新企业服务网',
    'keywords' => '企业诊断，政府资金项目申报，涉密资质，政府基金，税收优惠策划，知识产权规划，双软、重点软件企业、高新认定，计算机系统集成资质、涉密资质、安防资质',
    'description' => '中关村企业服务网帮助企业有效地利用各项政策资源实现企业最大利益      为企业提供全方位、多层次、专业化的“行政管家”式的服务，      为企业进行专业诊断、制订融资方案、知识产权战略、财税规划和资质认证等。',
    'release_point' => '',
    'default_style' => 'default',
    'template' => 'default',
    'setting' => 'array (
  \'upload_maxsize\' => \'2000\',
  \'upload_allowext\' => \'jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf\',
  \'watermark_enable\' => \'0\',
  \'watermark_minwidth\' => \'300\',
  \'watermark_minheight\' => \'300\',
  \'watermark_img\' => \'statics/images/water/http://www.zgcfw.org.cn/mark.gif\',
  \'watermark_pct\' => \'100\',
  \'watermark_quality\' => \'80\',
  \'watermark_pos\' => \'9\',
)',
    'uuid' => '',
    'url' => 'http://www.zgccfw.com/',
  ),
);
?>